import { Inter } from 'next/font/google'
import "./globals.css";
import { nunito_sans } from './utils/fonts';
import React from 'react';


const inter = Inter({ subsets: ['latin']})

export const metadata = {
  title: 'Mr. Lema Portfolio',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {

  
 return (
    <html className='scroll-smooth' lang="en">
      <head>
      <link rel="icon" href='/favicon.png' sizes="any" />
      </head>
    
      <body className={nunito_sans}>
          {children}
      </body>
    </html>
  )
}
