import { Inter } from 'next/font/google'
import "./globals.css";
import { nunito_sans } from './utils/fonts';
import React from 'react';
import BackToTopButton from './components/backToTopButton';
import NavbarNavigation from './components/NavbarNavigation';
import AuthProvider from './components/AuthProvider';
import { SessionProvider } from 'next-auth/react';


const inter = Inter({ subsets: ['latin']})

export const metadata = {
  title: 'ericktek',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {

 
 return (
    <html className='scroll-smooth' lang="en">
      <head>
      <link rel="icon" href='/favico.png' sizes="any" />
      </head>
      <body className={nunito_sans}>
      <AuthProvider>  
      <NavbarNavigation />
      <div className='min-h-screen'>
          {children}
          </div>
          <BackToTopButton />
          </AuthProvider> 
      </body>
    </html>
  )
}
